name: Build and push image

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v22
      - run: nix build .#docker

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag and Push
        env:
          GH_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
        run: |
          IMAGE="$(docker load -i result | awk '{print $3}')"
          docker tag "$IMAGE" "$GH_IMAGE"
          docker push "$GH_IMAGE"
